<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EtherGizmos.Common.$(MSBuildProjectName).UnitTests" />
    <InternalsVisibleTo Include="EtherGizmos.Common.$(MSBuildProjectName).IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Configuration\src\Configuration.Messaging\Configuration.Messaging.csproj" />
    <ProjectReference Include="..\..\..\Observability\src\Observability\Observability.csproj" />
  </ItemGroup>

</Project>
