<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EtherGizmos.Common.Notifications.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Notifications\Notifications.csproj" />
  </ItemGroup>

</Project>
