<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(MSBuildProjectName).UnitTests" />
    <InternalsVisibleTo Include="$(MSBuildProjectName).IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Configuration\Configuration.Messaging\Configuration.Messaging.csproj" />
    <ProjectReference Include="..\Messaging\Messaging.csproj" />
  </ItemGroup>

</Project>
